name: Rails CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd backend
          bundle install

      - name: Run tests
        run: |
          cd backend
          bundle exec rspec
